import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anna B - Développeuse Js Junior </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/myfavicon.png' />
      </Head>
      <Main />
      <About />
    </div>
  );
}
